### ISSUE TITLE
.expiry(key) for expire time

### ISSUE THREAD

**Issue by jnovack** [cyrus000/expire-memory#1]
Can you store the expire time with the key (now + expireTime), so that we can query until how long the key expires?

I would like to `expireMemory.expiry('key')` and be returned a javascript Date object (or milliseconds from epoch as int, coder's choice) so I can expect to know when the key will expire.

**Comment by cyrus000** [comment]
updated

**Comment by jnovack** [comment]
Excellent, thank you very much for your dedication to the cause!
